teacher('Perronne').
teacher('Hassenforder').
teacher('Thirion').
teacher('Bourgeois').
teacher('Studer').
teacher('Ruma').
teacher('Djedjick').
teacher('test').
teaches('Perronne','Android').
teaches('Hassenforder','C++').
teaches('test','Anglais').
